### PR TITLE
Feat/organizing components

### PR DESCRIPTION
**Pull request by sueherrera30**
Organizing routes with components and styles.

### CODE REVIEW

**Comment by TuentyFaiv** [comment]
remove unused variables in Profile.js

**Comment by sueherrera30** [comment]
it is the hook right?  so ldet my change  this

**Comment by TuentyFaiv** [comment]
check the bugs mentioned in sonarclub (bot)

**Comment by sueherrera30** [comment]
yes, im on that man.

**Comment by sueherrera30** [comment]
how the hell did you do that? it a vercel's magic feature?

**Comment by sueherrera30** [comment]
how the hell did you do that? it a vercel's magic feature?

**Comment by sueherrera30** [comment]
finally  u.u

**Pull request merged**
